title: UsefulScore
description: YOUR DESCRIPTION
theme: just-the-docs

url: https://cdreetz.github.io/UsefulScore/

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://cdreetz.github.io/UsefulScore/
